include/madara/knowledge/containers/CircularBufferConsumer.inl, include/madara/knowledge/containers/CircularBufferConsumerT.inl
Adding a check for local index when buffer has overflown.
=> Circular buffer updates

BUILD, WORKSPACE
=> Adding the files required for Bazel to work

.travis.yml, Tests.mpc, tests/test_knowledge_record.cpp
Added basica test coverage for KnowledgeRecord class
=> [SW-6924] Test Coverage (Initial KnowledgeRecord Test)

tests/test_knowledge_record.cpp
Fixed warnings in test_knowledge_record.cpp file
=> [SW-7239] Fix warnings in test_knowledge_record

.github/CODEOWNERS, include/madara/knowledge/Any.h, include/madara/knowledge/AnyRegistry.cpp, tests/transports/multicast/test_multicast.cpp
=> Don't throw on unregistered type

port/python/src/Madara.cpp
Request from Aatish to support wrapping vectors...
=> * Adding vector wraps to boost python support

include/madara/knowledge/CapnAdapt.h
Adding template parameters for non-default allocators. Needed for pointcloud types.
=> Adding template for std vector allocators

include/madara/filters/ssl/AESBufferFilter.cpp
- Switched to SHA256 hash
- Bumped up the number of hash rounds to 10000
- Added random salt
=> Modified AES key generation code

include/madara/knowledge/containers/NativeCircularBufferConsumer.h, include/madara/knowledge/containers/NativeCircularBufferConsumer.inl, include/madara/logger/Logger.cpp, include/madara/logger/Logger.h, tests/threads/test_threader_change_hertz.cpp
Went through submitted modules to conform to coding and style standards.  
Am highly available to fix an oversight, but believe this conforms closely to the standard.
=> Conform to Madara and Shield Style Guide.

include/madara/knowledge/containers/NativeCircularBufferConsumer.inl
And fixing clang compiler warnings about copy ellision
=> Checking for valid local index in inspect

port/python/src/FunctionDefaults.h, port/python/src/Madara.cpp, port/python/src/MadaraKnowledge.cpp
Added read_file to MadaraKnowledge.cpp as well as added new function default.
=> Python read

port/python/src/FunctionDefaults.h, port/python/src/MadaraKnowledge.cpp
Modified FunctionDefaults.h as well
=> Added read_file and various other methods

port/python/src/MadaraKnowledge.cpp
Rounded out various methods from madara/knowledgebase.cpp into MadaraKnowledge.cpp
=> Added missing methods to MadaraKnowledge.cpp

include/madara/knowledge/CheckpointPlayer.cpp
Question of why these exist remains to be investigated.
=>  Fix handling of empty STK layers

include/madara/knowledge/containers/NativeCircularBufferConsumer.h, include/madara/knowledge/containers/NativeCircularBufferConsumer.inl, tests/test_karl_containers.cpp
=> Update NCBC to further match CBC.

port/python/src/MadaraKnowledge.cpp
Modified .toi method for knowledgeRecord
=> Python fixes

scripts/linux/do_format.sh
=> Add do_format.sh

include/madara/utility/Utility.h, include/madara/utility/Utility.inl, tools/stk_inspect.cpp
* Added two new utility functions to aid with time related activities and splitting file contents into std::vector
* Added batch mode to stk_inspect
=> * Added initial batch mode

port/python/src/Madara.cpp, port/python/src/MadaraKnowledge.cpp
Added KnowledgeBase::set methods for direct KR entry and from/to_pystrings
=> Python port fixes

port/python/src/Madara.cpp, port/python/src/MadaraKnowledge.cpp
=> Added KnowledgeRecord method

.travis.yml, include/madara/utility/NamedVectorCombinator.h, tests/settings/named_vectors/thread1.read, tests/settings/named_vectors/thread1.write, tests/settings/named_vectors/thread2.read, tests/settings/named_vectors/thread2.write, tests/test_utility.cpp, tools/karl.cpp, tools/stk_inspect.cpp
Adding Combinator and attempting to see if .travis.yml changes will give us Xenial support
=> Combinator

include/madara/knowledge/KnowledgeBaseImpl.cpp, include/madara/knowledge/KnowledgeBaseImpl.h, include/madara/knowledge/KnowledgeBaseImpl.inl
=> (SW-8901) send_modifieds without holding context lock

include/madara/knowledge/CapnAdapt.h
=> Adding enum list support

.gitignore, include/madara/transport/BasicASIOTransport.h, include/madara/transport/udp/UdpTransport.cpp, include/madara/transport/udp/UdpTransport.h
* Updating UdpTransport to allow it to be used publicly for send/receive
=> Udp changes

CMakeLists.txt, include/madara/expression/ExpressionTree.cpp, include/madara/expression/ExpressionTree.h, include/madara/knowledge/CompiledExpression.h, include/madara/knowledge/Functions.h, include/madara/knowledge/ThreadSafeContext.cpp, include/madara/logger/Logger.h, include/madara/utility/Utility.inl, scripts/linux/cmake.sh, scripts/projects/CMakeLists.txt
* Fixing all cmake warnings on Ubuntu 22. Need to check Ubuntu 20
* Added cmake build file. Will work on wiki update for installation
=> Cmake changes

scripts/linux/cmake.sh
Adding help menu and options for tests, clang, etc. to the cmake.sh script
=> Cmake script updates
